// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube/internal"
)

// ## # Data Source: Portfolio
//
// # Use this data source to get a Sonarqube portfolio resource
//
// ## Example Usage
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sonarqube.LookupPortfolio(ctx, &sonarqube.LookupPortfolioArgs{
//				Key: "portfolio-key",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
func LookupPortfolio(ctx *pulumi.Context, args *LookupPortfolioArgs, opts ...pulumi.InvokeOption) (*LookupPortfolioResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPortfolioResult
	err := ctx.Invoke("sonarqube:index/getPortfolio:getPortfolio", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPortfolio.
type LookupPortfolioArgs struct {
	Key string `pulumi:"key"`
}

// A collection of values returned by getPortfolio.
type LookupPortfolioResult struct {
	Branch      string `pulumi:"branch"`
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id            string   `pulumi:"id"`
	Key           string   `pulumi:"key"`
	Name          string   `pulumi:"name"`
	Qualifier     string   `pulumi:"qualifier"`
	Regexp        string   `pulumi:"regexp"`
	SelectionMode string   `pulumi:"selectionMode"`
	Tags          []string `pulumi:"tags"`
	Visibility    string   `pulumi:"visibility"`
}

func LookupPortfolioOutput(ctx *pulumi.Context, args LookupPortfolioOutputArgs, opts ...pulumi.InvokeOption) LookupPortfolioResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPortfolioResult, error) {
			args := v.(LookupPortfolioArgs)
			r, err := LookupPortfolio(ctx, &args, opts...)
			var s LookupPortfolioResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupPortfolioResultOutput)
}

// A collection of arguments for invoking getPortfolio.
type LookupPortfolioOutputArgs struct {
	Key pulumi.StringInput `pulumi:"key"`
}

func (LookupPortfolioOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPortfolioArgs)(nil)).Elem()
}

// A collection of values returned by getPortfolio.
type LookupPortfolioResultOutput struct{ *pulumi.OutputState }

func (LookupPortfolioResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPortfolioResult)(nil)).Elem()
}

func (o LookupPortfolioResultOutput) ToLookupPortfolioResultOutput() LookupPortfolioResultOutput {
	return o
}

func (o LookupPortfolioResultOutput) ToLookupPortfolioResultOutputWithContext(ctx context.Context) LookupPortfolioResultOutput {
	return o
}

func (o LookupPortfolioResultOutput) Branch() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Branch }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupPortfolioResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Key }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Qualifier() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Qualifier }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Regexp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Regexp }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) SelectionMode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.SelectionMode }).(pulumi.StringOutput)
}

func (o LookupPortfolioResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupPortfolioResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

func (o LookupPortfolioResultOutput) Visibility() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPortfolioResult) string { return v.Visibility }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPortfolioResultOutput{})
}
