// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube/internal"
)

// ## # UserToken
//
// Provides a Sonarqube User token resource. This can be used to manage Sonarqube User tokens.
//
// ## Example: create a user, user token and output the token value
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			user, err := sonarqube.NewUser(ctx, "user", &sonarqube.UserArgs{
//				LoginName: pulumi.String("terraform-test"),
//				Password:  pulumi.String("secret-sauce37!"),
//			})
//			if err != nil {
//				return err
//			}
//			token, err := sonarqube.NewUserToken(ctx, "token", &sonarqube.UserTokenArgs{
//				LoginName: user.LoginName,
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("userToken", token.Token)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Example: create an expiring global analysis token and output the token value
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			token, err := sonarqube.NewUserToken(ctx, "token", &sonarqube.UserTokenArgs{
//				Type:           pulumi.String("GLOBAL_ANALYSIS_TOKEN"),
//				ExpirationDate: pulumi.String("2099-01-01"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("globalAnalysisToken", token.Token)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Example: create a project, project analysis token, and output the token value
//
// <!--Start PulumiCodeChooser -->
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/saggafarsyad/pulumi-sonarqube/sdk/go/sonarqube"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			token, err := sonarqube.NewUserToken(ctx, "token", &sonarqube.UserTokenArgs{
//				Type:       pulumi.String("PROJECT_ANALYSIS_TOKEN"),
//				ProjectKey: pulumi.String("my-project"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("projectAnalysisToken", token.Token)
//			return nil
//		})
//	}
//
// ```
// <!--End PulumiCodeChooser -->
//
// ## Import
//
// Import is not supported for this resource.
type UserToken struct {
	pulumi.CustomResourceState

	ExpirationDate pulumi.StringOutput    `pulumi:"expirationDate"`
	LoginName      pulumi.StringPtrOutput `pulumi:"loginName"`
	Name           pulumi.StringOutput    `pulumi:"name"`
	ProjectKey     pulumi.StringPtrOutput `pulumi:"projectKey"`
	Token          pulumi.StringOutput    `pulumi:"token"`
	Type           pulumi.StringPtrOutput `pulumi:"type"`
}

// NewUserToken registers a new resource with the given unique name, arguments, and options.
func NewUserToken(ctx *pulumi.Context,
	name string, args *UserTokenArgs, opts ...pulumi.ResourceOption) (*UserToken, error) {
	if args == nil {
		args = &UserTokenArgs{}
	}

	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource UserToken
	err := ctx.RegisterResource("sonarqube:index/userToken:UserToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUserToken gets an existing UserToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserTokenState, opts ...pulumi.ResourceOption) (*UserToken, error) {
	var resource UserToken
	err := ctx.ReadResource("sonarqube:index/userToken:UserToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UserToken resources.
type userTokenState struct {
	ExpirationDate *string `pulumi:"expirationDate"`
	LoginName      *string `pulumi:"loginName"`
	Name           *string `pulumi:"name"`
	ProjectKey     *string `pulumi:"projectKey"`
	Token          *string `pulumi:"token"`
	Type           *string `pulumi:"type"`
}

type UserTokenState struct {
	ExpirationDate pulumi.StringPtrInput
	LoginName      pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	ProjectKey     pulumi.StringPtrInput
	Token          pulumi.StringPtrInput
	Type           pulumi.StringPtrInput
}

func (UserTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*userTokenState)(nil)).Elem()
}

type userTokenArgs struct {
	ExpirationDate *string `pulumi:"expirationDate"`
	LoginName      *string `pulumi:"loginName"`
	Name           *string `pulumi:"name"`
	ProjectKey     *string `pulumi:"projectKey"`
	Type           *string `pulumi:"type"`
}

// The set of arguments for constructing a UserToken resource.
type UserTokenArgs struct {
	ExpirationDate pulumi.StringPtrInput
	LoginName      pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	ProjectKey     pulumi.StringPtrInput
	Type           pulumi.StringPtrInput
}

func (UserTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userTokenArgs)(nil)).Elem()
}

type UserTokenInput interface {
	pulumi.Input

	ToUserTokenOutput() UserTokenOutput
	ToUserTokenOutputWithContext(ctx context.Context) UserTokenOutput
}

func (*UserToken) ElementType() reflect.Type {
	return reflect.TypeOf((**UserToken)(nil)).Elem()
}

func (i *UserToken) ToUserTokenOutput() UserTokenOutput {
	return i.ToUserTokenOutputWithContext(context.Background())
}

func (i *UserToken) ToUserTokenOutputWithContext(ctx context.Context) UserTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserTokenOutput)
}

// UserTokenArrayInput is an input type that accepts UserTokenArray and UserTokenArrayOutput values.
// You can construct a concrete instance of `UserTokenArrayInput` via:
//
//	UserTokenArray{ UserTokenArgs{...} }
type UserTokenArrayInput interface {
	pulumi.Input

	ToUserTokenArrayOutput() UserTokenArrayOutput
	ToUserTokenArrayOutputWithContext(context.Context) UserTokenArrayOutput
}

type UserTokenArray []UserTokenInput

func (UserTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserToken)(nil)).Elem()
}

func (i UserTokenArray) ToUserTokenArrayOutput() UserTokenArrayOutput {
	return i.ToUserTokenArrayOutputWithContext(context.Background())
}

func (i UserTokenArray) ToUserTokenArrayOutputWithContext(ctx context.Context) UserTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserTokenArrayOutput)
}

// UserTokenMapInput is an input type that accepts UserTokenMap and UserTokenMapOutput values.
// You can construct a concrete instance of `UserTokenMapInput` via:
//
//	UserTokenMap{ "key": UserTokenArgs{...} }
type UserTokenMapInput interface {
	pulumi.Input

	ToUserTokenMapOutput() UserTokenMapOutput
	ToUserTokenMapOutputWithContext(context.Context) UserTokenMapOutput
}

type UserTokenMap map[string]UserTokenInput

func (UserTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserToken)(nil)).Elem()
}

func (i UserTokenMap) ToUserTokenMapOutput() UserTokenMapOutput {
	return i.ToUserTokenMapOutputWithContext(context.Background())
}

func (i UserTokenMap) ToUserTokenMapOutputWithContext(ctx context.Context) UserTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserTokenMapOutput)
}

type UserTokenOutput struct{ *pulumi.OutputState }

func (UserTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UserToken)(nil)).Elem()
}

func (o UserTokenOutput) ToUserTokenOutput() UserTokenOutput {
	return o
}

func (o UserTokenOutput) ToUserTokenOutputWithContext(ctx context.Context) UserTokenOutput {
	return o
}

func (o UserTokenOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o UserTokenOutput) LoginName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringPtrOutput { return v.LoginName }).(pulumi.StringPtrOutput)
}

func (o UserTokenOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o UserTokenOutput) ProjectKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringPtrOutput { return v.ProjectKey }).(pulumi.StringPtrOutput)
}

func (o UserTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

func (o UserTokenOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserToken) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

type UserTokenArrayOutput struct{ *pulumi.OutputState }

func (UserTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserToken)(nil)).Elem()
}

func (o UserTokenArrayOutput) ToUserTokenArrayOutput() UserTokenArrayOutput {
	return o
}

func (o UserTokenArrayOutput) ToUserTokenArrayOutputWithContext(ctx context.Context) UserTokenArrayOutput {
	return o
}

func (o UserTokenArrayOutput) Index(i pulumi.IntInput) UserTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *UserToken {
		return vs[0].([]*UserToken)[vs[1].(int)]
	}).(UserTokenOutput)
}

type UserTokenMapOutput struct{ *pulumi.OutputState }

func (UserTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserToken)(nil)).Elem()
}

func (o UserTokenMapOutput) ToUserTokenMapOutput() UserTokenMapOutput {
	return o
}

func (o UserTokenMapOutput) ToUserTokenMapOutputWithContext(ctx context.Context) UserTokenMapOutput {
	return o
}

func (o UserTokenMapOutput) MapIndex(k pulumi.StringInput) UserTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *UserToken {
		return vs[0].(map[string]*UserToken)[vs[1].(string)]
	}).(UserTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserTokenInput)(nil)).Elem(), &UserToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserTokenArrayInput)(nil)).Elem(), UserTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserTokenMapInput)(nil)).Elem(), UserTokenMap{})
	pulumi.RegisterOutputType(UserTokenOutput{})
	pulumi.RegisterOutputType(UserTokenArrayOutput{})
	pulumi.RegisterOutputType(UserTokenMapOutput{})
}
