# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

anonymizeUserOnDelete: Optional[bool]
"""
Allows anonymizing users on destroy. Requires Sonarqube version >= 9.7.
"""

host: Optional[str]

httpProxy: Optional[str]

installedEdition: Optional[str]

installedVersion: Optional[str]

pass: Optional[str]

tlsInsecureSkipVerify: Optional[bool]
"""
Allows ignoring insecure certificates when set to true. Defaults to false. Disabling TLS verification is dangerous and
should only be done for local testing.
"""

token: Optional[str]

user: Optional[str]

