# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('sonarqube')


class _ExportableConfig(types.ModuleType):
    @property
    def anonymize_user_on_delete(self) -> Optional[bool]:
        """
        Allows anonymizing users on destroy. Requires Sonarqube version >= 9.7.
        """
        return __config__.get_bool('anonymizeUserOnDelete')

    @property
    def host(self) -> Optional[str]:
        return __config__.get('host')

    @property
    def http_proxy(self) -> Optional[str]:
        return __config__.get('httpProxy')

    @property
    def installed_edition(self) -> Optional[str]:
        return __config__.get('installedEdition')

    @property
    def installed_version(self) -> Optional[str]:
        return __config__.get('installedVersion')

    @property
    def pass_(self) -> Optional[str]:
        return __config__.get('pass')

    @property
    def tls_insecure_skip_verify(self) -> Optional[bool]:
        """
        Allows ignoring insecure certificates when set to true. Defaults to false. Disabling TLS verification is dangerous and
        should only be done for local testing.
        """
        return __config__.get_bool('tlsInsecureSkipVerify')

    @property
    def token(self) -> Optional[str]:
        return __config__.get('token')

    @property
    def user(self) -> Optional[str]:
        return __config__.get('user')

