// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface PortfolioSelectedProject {
    /**
     * The key of a project to add to the portfolio
     */
    projectKey: pulumi.Input<string>;
    /**
     * A list of branches of the project to add to the portfolio. Defaults to the `MAIN BRANCH` of the repo if omitted
     *
     * Here is an example of how this option can be leveraged:
     */
    selectedBranches?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface ProjectSetting {
    /**
     * Setting field values for the supplied key
     */
    fieldValues?: pulumi.Input<pulumi.Input<{[key: string]: any}>[]>;
    /**
     * Setting key
     */
    key: pulumi.Input<string>;
    /**
     * Setting a value for the supplied key
     */
    value?: pulumi.Input<string>;
    /**
     * Setting multi values for the supplied key
     */
    values?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface QualitygateCondition {
    id?: pulumi.Input<string>;
    metric: pulumi.Input<string>;
    op: pulumi.Input<string>;
    threshold: pulumi.Input<string>;
}
