// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube.Inputs
{

    public sealed class QualitygateConditionGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("metric", required: true)]
        public Input<string> Metric { get; set; } = null!;

        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        [Input("threshold", required: true)]
        public Input<string> Threshold { get; set; } = null!;

        public QualitygateConditionGetArgs()
        {
        }
        public static new QualitygateConditionGetArgs Empty => new QualitygateConditionGetArgs();
    }
}
