// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # sonarqube.AlmGitlab
 *
 * Provides a Sonarqube GitLab Alm/Devops Platform Integration resource. This can be used to create and manage a Alm/Devops
 * Platform Integration for GitLab.
 *
 * ## Example: Create a GitHub Alm Integration
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const gitlab_alm = new sonarqube.AlmGitlab("gitlab-alm", {
 *     key: "myalm",
 *     personalAccessToken: "my_personal_access_token",
 *     url: "https://gitlab.com/api/v4",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export class AlmGitlab extends pulumi.CustomResource {
    /**
     * Get an existing AlmGitlab resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlmGitlabState, opts?: pulumi.CustomResourceOptions): AlmGitlab {
        return new AlmGitlab(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/almGitlab:AlmGitlab';

    /**
     * Returns true if the given object is an instance of AlmGitlab.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlmGitlab {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlmGitlab.__pulumiType;
    }

    public readonly key!: pulumi.Output<string>;
    public readonly personalAccessToken!: pulumi.Output<string>;
    public readonly url!: pulumi.Output<string>;

    /**
     * Create a AlmGitlab resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlmGitlabArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlmGitlabArgs | AlmGitlabState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlmGitlabState | undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["personalAccessToken"] = state ? state.personalAccessToken : undefined;
            resourceInputs["url"] = state ? state.url : undefined;
        } else {
            const args = argsOrState as AlmGitlabArgs | undefined;
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if ((!args || args.personalAccessToken === undefined) && !opts.urn) {
                throw new Error("Missing required property 'personalAccessToken'");
            }
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["personalAccessToken"] = args?.personalAccessToken ? pulumi.secret(args.personalAccessToken) : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["personalAccessToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(AlmGitlab.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AlmGitlab resources.
 */
export interface AlmGitlabState {
    key?: pulumi.Input<string>;
    personalAccessToken?: pulumi.Input<string>;
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AlmGitlab resource.
 */
export interface AlmGitlabArgs {
    key: pulumi.Input<string>;
    personalAccessToken: pulumi.Input<string>;
    url: pulumi.Input<string>;
}
