// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## # sonarqube.PermissionTemplate
 *
 * Provides a Sonarqube Permission template resource. This can be used to create and manage Sonarqube Permission
 * templates.
 *
 * ## Example: create a template
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sonarqube from "@pulumi/sonarqube";
 *
 * const template = new sonarqube.PermissionTemplate("template", {
 *     description: "These are internal projects",
 *     projectKeyPattern: "internal.*",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 *
 * ## Import
 *
 * Templates can be imported using their ID
 *
 * terraform
 *
 * ```sh
 * $ pulumi import sonarqube:index/permissionTemplate:PermissionTemplate template ABC_defghij
 * ```
 */
export class PermissionTemplate extends pulumi.CustomResource {
    /**
     * Get an existing PermissionTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PermissionTemplateState, opts?: pulumi.CustomResourceOptions): PermissionTemplate {
        return new PermissionTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/permissionTemplate:PermissionTemplate';

    /**
     * Returns true if the given object is an instance of PermissionTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PermissionTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PermissionTemplate.__pulumiType;
    }

    public readonly default!: pulumi.Output<boolean | undefined>;
    public readonly description!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly projectKeyPattern!: pulumi.Output<string | undefined>;

    /**
     * Create a PermissionTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PermissionTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PermissionTemplateArgs | PermissionTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PermissionTemplateState | undefined;
            resourceInputs["default"] = state ? state.default : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["projectKeyPattern"] = state ? state.projectKeyPattern : undefined;
        } else {
            const args = argsOrState as PermissionTemplateArgs | undefined;
            resourceInputs["default"] = args ? args.default : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["projectKeyPattern"] = args ? args.projectKeyPattern : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PermissionTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PermissionTemplate resources.
 */
export interface PermissionTemplateState {
    default?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    projectKeyPattern?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PermissionTemplate resource.
 */
export interface PermissionTemplateArgs {
    default?: pulumi.Input<boolean>;
    description?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    projectKeyPattern?: pulumi.Input<string>;
}
